# Generated by Django 6.0.6 on 2026-06-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("images", models.ImageField(blank=True, upload_to="places/")),
                ("name", models.CharField(max_length=100)),
                ("recommended_level", models.IntegerField(default=1)),
                ("category", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=200)),
                ("descirption", models.TextField(blank=True)),
                ("opening_hours", models.CharField(blank=True, max_length=100)),
                ("tel", models.CharField(blank=True, max_length=20)),
                ("has_wifi", models.BooleanField(default=False)),
                ("has_con", models.BooleanField(default=False)),
                ("has_kiosk", models.BooleanField(default=False)),
                ("has_single_seat", models.BooleanField(default=False)),
                ("has_partition", models.BooleanField(default=False)),
                ("parking_available", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
