# Generated by Django 6.0.6 on 2026-06-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_purpose_tag_visittime_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="visit_time",
            new_name="visit_times",
        ),
    ]
