# Generated by Django 6.0.6 on 2026-06-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_placelike"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placelike",
            name="created_at",
        ),
    ]
