# Generated by Django 6.0.6 on 2026-06-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_remove_placelike_created_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="descirption",
            new_name="descirptions",
        ),
        migrations.AddField(
            model_name="place",
            name="kakao_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="place",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="longtitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
