# Generated by Django 6.0.6 on 2026-06-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_rename_descirption_place_descirptions_place_kakao_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="longtitude",
            new_name="longitude",
        ),
    ]
