# Generated by Django 6.0.6 on 2026-06-23 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_reviewimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="parking_available",
        ),
    ]
