# Generated by Django 6.0.6 on 2026-06-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_place_parking_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="purpose",
            name="group",
            field=models.CharField(
                choices=[
                    ("food", "카페/음식점"),
                    ("culture", "전시/공연/소품"),
                    ("common", "공통"),
                ],
                default="common",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="group",
            field=models.CharField(
                choices=[
                    ("food", "카페/음식점"),
                    ("culture", "전시/공연/소품"),
                    ("common", "공통"),
                ],
                default="common",
                max_length=10,
            ),
        ),
    ]
