# Generated by Django 6.0.6 on 2026-06-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_purpose_group_tag_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="stay_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("30분 이하", "30분이하"),
                    ("30분-1시간", "30분-1시간"),
                    ("1시간-2시간", "1시간-2시간"),
                    ("2시간 이상", "2시간 이상"),
                ],
                max_length=20,
            ),
        ),
    ]
