# Generated by Django 6.0.6 on 2026-06-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_review_stay_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="followings",
            field=models.ManyToManyField(
                blank=True, related_name="followers", to="main.profile"
            ),
        ),
    ]
