# Generated by Django 6.0.6 on 2026-06-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_profile_followings"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
