# Generated by Django 6.0.6 on 2026-06-23 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_profile_image"),
        ("main", "0016_review_likes"),
    ]

    operations = []
